# Generated by Django 2.2.5 on 2023-03-05 15:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Mu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_audio', models.FileField(upload_to='media_mp3', validators=[django.core.validators.FileExtensionValidator(['mp3'])])),
                ('content', models.TextField()),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='予定日')),
                ('like', models.ManyToManyField(blank=True, related_name='related_post', to=settings.AUTH_USER_MODEL)),
                ('mylist', models.ManyToManyField(blank=True, related_name='mylist_post', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-selected_at',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post_image', models.ImageField(upload_to='post_image', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('content', models.TextField()),
                ('selected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='予定日')),
                ('like2', models.ManyToManyField(blank=True, related_name='related_posts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-selected_at',),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_image', models.ImageField(blank=True, upload_to='profile_pics', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
